resetted array manipulation 1
moamel-hashim/c1021-code-solutions pull request #66
Opened 2021-12-08 06:01 UTC by moamel-hashim

2021-12-08 06:01 UTC, moamel-hashim commented
![Capture](https://user-images.githubusercontent.com/90476994/145156561-ecdfeefd-fb7f-4861-ac6f-625d2b4c2667.PNG)

2021-12-08 15:45 UTC, thebearingedge requested changes

2021-12-08 15:45 UTC, thebearingedge commented on array-manipulation-1/src/head.js
> +  }
This condition is never true, you can remove it.

2021-12-08 15:45 UTC, thebearingedge commented on array-manipulation-1/src/last.js
>    }
This condition is never true, you can remove it. Objects and arrays never equal each other because they are compared with their memory address and not what's inside of them, you can try it in the console.

2021-12-09 02:28 UTC, moamel-hashim commented
![Capture](https://user-images.githubusercontent.com/90476994/145323283-32e6021a-e174-4ee7-95a4-8edbcb1ffef3.PNG)
![Capture](https://user-images.githubusercontent.com/90476994/145323355-ff2bf3a7-603b-4073-8737-8b98af8a5a3d.PNG)

2021-12-09 03:33 UTC, thebearingedge approved these changes

2021-12-09 03:34 UTC, merged